    <!-- starts footer -->
		<h2 class="section_header">
			<hr class="left visible-desktop">
			<span>Feedback</span>
			<hr class="right visible-desktop">
		</h2>
            <div class="row form">
                <div class="span6">
                    <form class="form-horizontal">
                        <div class="control-group">
                                <label class="control-label" for="inputName">Name</label>
                                <div class="controls">
                                    <input type="text" class="span4" id="inputName">
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputEmail">Email</label>
                                <div class="controls">
                                    <input type="text" class="span4" id="inputEmail">
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputPhone">Phone</label>
                                <div class="controls">
                                    <input type="text" class="span4" id="inputPhone">
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputCity">City</label>
                                <div class="controls">
                                    <input type="text" class="span4" id="inputCity">
                                </div>
                            </div>
                            <div class="control-group">
                                <label class="control-label" for="inputComment">Comment</label>
                                <div class="controls">
                                    <textarea class="span4" id="inputComment" rows="6"></textarea>
                                </div>
                            </div>
                            <div class="control-group">
                                <div class="controls action">
                                    <button type="submit" class="btn">Send</button>
                                </div>
                            </div>
                        </form>
                </div>
                <div class="span5 offset1">
                    <div class="address">
                        <h3>Address</h3>
                        <p>
                            7086 Hollywood Blvd. 
                            <br> Los Angeles, CA 90028
                        </p>
                        <div class="info">
                            <i class="contact phone"></i>
                            1 562 761 1506
                        </div>
                        <div class="info">
                            <i class="contact email"></i>
                            evo@citypackr.com
                        </div>
                        <hr>
                        <h3>Social media</h3>
                        <div class="social">
                            <a href="#"><i class="social tw"></i></a>
                            <a href="#"><i class="social fb"></i></a>
                            <a href="#"><i class="social flickr"></i></a>
                            <a href="#"><i class="social in"></i></a>
                            <a href="#"><i class="social gp"></i></a>
                            <a href="#"><i class="social pin"></i></a>
                            <a href="#"><i class="social tumblr"></i></a>
                            <br>
                            <a href="#"><i class="social wp"></i></a>
                            <a href="#"><i class="social yt"></i></a>
                            <a href="#"><i class="social vim"></i></a>
                            <a href="#"><i class="social picasa"></i></a>
                            <a href="#"><i class="social forrst"></i></a>
                            <a href="#"><i class="social rss"></i></a>
                            <a href="#"><i class="social myspace"></i></a>
                        </div>
                    </div>
                </div>
            </div>
<script type="text/javascript">

  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-37077434-1']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();

</script>
<script src="http://www.citypackr.com/measure_theme/measure/js/theme.js"></script>
</body>
</html>